### PR TITLE
Centralizing runner tags a bit

### PR DESCRIPTION
**Pull request by duallain**
You can't import twice, so separating imports from the jobs.

### CODE REVIEW

**Comment by duallain** [comment]
@glogiotatidis I noticed that the jobs for infra-services weren't going to the new runners, what do you think of this change as a way of preventing the need to repeat ourselves?

**Comment by glogiotatidis** [comment]
> @glogiotatidis I noticed that the jobs for infra-services weren't going to the new runners, what do you think of this change as a way of preventing the need to repeat ourselves?

That can't be the case, b/c I was testing the IAM permissions the other day. Our runners [are set](https://github.com/mozmeao/infra-services/blob/master/gitlab-runners/packer/ansible/files/defaults/playbook.yml#L36) to run untagged code and shared runners are disabled from the [project settings](https://gitlab.com/mozmeao/infra-services/-/settings/ci_cd)

Since we will be removing GCP infra, I argue to remove the tags altogether and only use them if something needs to run to a specific region / setup. It should be simpler to maintain and . We should also disable shared runners via the WebUI for all our projects (i believe this is the case for most, if nto all). What do you think?

**Comment by duallain** [comment]
Hmm, this was the job that was stuck - https://gitlab.com/mozmeao/infra-services/-/jobs/547371686

the wrangler job has the old aws tags.  I think the functional changes in this branch of infra-services was just to change tags, I did a few refactors, but I think that's got us back to the permissions issue. (https://gitlab.com/mozmeao/infra-services/pipelines/144911048)

I'm ok with that plan in general.  If possible, can we move from working pipeline to working pipeline? Since gcp runner still exists for at least a little while (we'll need to migrate bedrock out of gcp before we can tear it down), it seems like it might be best to keep the tags we have.

We should disable the gitlab provided runners (I think that's what you mean by shared). Probably safe to do today?

**Comment by glogiotatidis** [comment]
> Hmm, this was the job that was stuck - https://gitlab.com/mozmeao/infra-services/-/jobs/547371686

Yeah b/c it's using the old tags. 

> We should disable the gitlab provided runners (I think that's what you mean by shared). Probably safe to do today?

Most of our projects already had them disabled. I switched a few other projects (including this one) to the same setting. (BTW GitLab calls them Shared Runners)

**Review by glogiotatidis — APPROVED** [review]
Let's merge and re-eval tags when GCP is out of the picture. Don't forget to squash!

:rocket:

**Pull request merged**
